name: Docker Image CI

on:
    push:
        branches: ["main"]
        

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - name: docker login
              env:
                  DOCKER_USER: jackbailey
                  DOCKER_PASS: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
              run: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASS
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag jackbailey/nextcloud
            - name: Docker Push
              run: docker push jackbailey/nextcloud --all-tags
